kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: postgresql-route
  namespace: {{ .Values.global.namespace }}
spec:
  host: postgres.auth.db
  to:
    kind: Service
    name: {{ .Values.postgresql.name }}-service
  port:
    targetPort: 5432