apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.name }}-secret
  labels:
    app: {{ .Values.postgresql.name }}
    component: database
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}
  database-name: {{ .Values.postgresql.database | b64enc | quote }}
  username: {{ .Values.postgresql.username | b64enc | quote }}